# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b0cdd346652124051e138c7fec92758aeb1cff0efbdb6edf858fda7b4a7e3ecf37d0730c87b036b99c4afdf232edd4c4ae615906bab57cc6b60df8e319eb7ed

test:
  secret_key_base: db94046cce2c4486fb534eaf65596764888c45ec5ad75ae90430b3a56389d618efe6e038109b4400cc14e927dcba3022c312878ee8aff53062e78caf03b655cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
